<?php
require_once __DIR__ . "/../config/Database.php";
require_once __DIR__ . "/../model/Article.php";
use PHPUnit\Framework\TestCase;

class ArticleTest extends TestCase {

	private $article;

	protected function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->article = new Article();
	}

	protected function tearDown()
	{
		parent::tearDown(); // TODO: Change the autogenerated stub
		$this->article = NULL;
	}

	public function testGetArticlesItemByID()
	{
		$result = $this->article->getArticlesItemByID(1);
		$this->assertEquals("Lorem ipsum dolor sit amet my rumba", $result['title']);
		$this->assertEquals("handy", $result['author']);
		$this->assertTrue(true);
	}

	public function testGetArticlesList()
	{
		$result = $this->article->getArticlesList(1,10);
		$this->assertNotEmpty($result);
	}

	public function testInsertArticle()
	{
		$articleArray = [
			'title' => 'Test Title',
			'author' => 'testauthor',
			'body' => 'test body'
		];
		$result = $this->article->insertArticle($articleArray);
		$this->assertEquals('Статья успешно добавлена', $result[0]);
	}

	public function testUpdateArticle()
	{
		$articleArray = [
			'title' => 'Test Title',
			'author' => 'testauthor',
			'body' => 'test body 2'
		];
		$this->articleArray = array(['id' => 23]);
		$result = $this->article->updateArticle($articleArray);
		$this->assertEquals('Статья успешно отредактирована', $result[0]);
	}

	public function testDeleteArticle()
	{
		$id = 23;
		$result = $this->article->deleteArticle($id);
		$this->assertTrue($result);

	}
}